### PR TITLE
1st

### PR DESCRIPTION
**Pull request by heyyitskk**
# Description

my first successful merge

### CODE REVIEW

**Comment by ghost** [comment]
Reviewing this right now, let's see...

**Review by ghost — CHANGES_REQUESTED** [review]
Oh looks like the `CODEOWNERS` file I gave you is outdated. It has **Carl listed**, but he's... no longer with the company. Could you **remove him from the file**, but not from our hearts, and push that change?

**Comment by ghost** [comment]
Reviewing this right now, let's see...

**Review by ghost — CHANGES_REQUESTED** [review]
Oh looks like the `CODEOWNERS` file I gave you is outdated. It has **Carl listed**, but he's... no longer with the company. Could you **remove him from the file**, but not from our hearts, and push that change?

**Comment by heyyitskk** [comment]
sorry i guess i messed up

**Pull request closed without merging**
